/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class InputImage {
  constructor(buf: Buffer, width: number, height: number)
  /** decode an encoded image (jpeg, png, gif, webp) into an InputImage */
  static fromImage(buf: Buffer): InputImage
}
export type NapiInputImage = InputImage

export declare function colors(input: InputImage): Array<JsColor>

export declare function colorsWithConfig(
  input: InputImage,
  config: JsConfig,
): Array<JsColor>

export interface JsColor {
  r: number
  g: number
  b: number
}

export interface JsConfig {
  maskSaturatedThreshold: number
  maskWeight: number
  maskWeightedCountsWeight: number
  chromaWeight: number
}
